frequency: 10 # Match this to your message publish frequencies!

two_d_mode: true # Enable 2D mode! 3D variables will be ignored (Z, roll, pitch, etc.)

publish_tf: true

map_frame: map
odom_frame: odom_fused #odom
base_link_frame: base_footprint
world_frame: odom_fused #odom

odom0: /raw_odom

#[x_pos   , y_pos    , z_pos,
# roll    , pitch    , yaw,
# x_vel   , y_vel    , z_vel,
# roll_vel, pitch_vel, yaw_vel,
# x_accel , y_accel  , z_accel]

odom0_config: [false, false, false,
               false, false, false,
               true , true , false,
               false, false, true,
               false, false, false]
              
odom0_differential: true
odom0_relative: false

#imu0: /imu
#imu0_config:  [false, false, false,
#               false, false, true,
#               false, false, false,
#               false, false, true,
#               false, false, false]
#imu0_differential: true  

pose0: /slam_out_pose
pose0_config: [false, false, false,
               false, false, true,
               true , true , false,
               false, false, true,
               false, false, false]
